name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Start API, run tests, kill API
        run: | 
          (cd BoxFactoryAPI && dotnet run) &
          api_pid=$!  # Get the process ID of the API
          
          # Wait for the API to become available
          for i in {1..60}; do  # Wait for up to 60 seconds (adjust as needed)
          sleep 1
          response=$(curl -sSf http://localhost:5000)  # Try to make a request to the API
          if [ "$?" -eq 0 ] && [ "$response" == "API is up!" ]; then
          break  # API is up, break out of the loop
          fi
          done
          
          if [ "$i" -eq 60 ]; then
          echo "API did not start within the timeout."
          exit 1
          fi
          
          (cd Tests && dotnet test)  # Run tests after API is up and running
          
          # Kill the API
          kill -9 $api_pid
        env:
          box_conn: ${{secrets.BOX_CONN}}