name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER testuser PASSWORD 'password'" --command="\du"

      - name: Create additional database
        run: |
            sudo -u postgres createdb TestDatabase --owner=testuser 
            PGPASSWORD=password 
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Start API, run tests, kill API
        run: (cd BoxFactoryAPI && dotnet run) &
          (sleep 20 && cd Tests && dotnet test) &
          (sleep 40 && kill -9 $(lsof -t -i:5000))
        env:
          box_conn: Host=localhost;Database=TestDatabase;Username=testuser;Password=password